### PR TITLE
fix: move index to root and update paths

### PR DESCRIPTION
**Pull request by MattCrook**
Someone approve this and I will merge to `master`.
*Once it is merged, make sure you don't have any outstanding changes before you pull (and update local copy of `master`.)

1. Get to a state where you are ok committing, or discard changes or stash them on your personal development branch. Then, follow below steps:
2. `git checkout master`
3. `git status` (to make sure you don't have any outstanding changes) which we shouldn't (bc its `master`)
4. Either `git fetch` (manually verify) and then `git merge master`.
5. Or just `git pull origin master`.
6. `git checkout [local-branch]` 
7. `git merge master` (this is what merges the changes in this PR to your local branch. *Note, might have merge conflicts.

### CODE REVIEW

**Comment by agreen2601** [comment]
good to go

**Comment by CoopNich** [comment]
Sick bro

**Comment by tyler-simeone** [comment]
Changes confirmed and pages now work without errors.

**Review by tyler-simeone — APPROVED** [review]

**Review by CoopNich — APPROVED** [review]

**Review by agreen2601 — COMMENTED** [review]
good

**Pull request merged**
